### ISSUE TITLE
bad fonts encoding

### ISSUE THREAD

**Issue by Germano0** [ProtonMail/proton-bridge#13]
the bridge has many interfaces where is not possible to read the chars. See screenshot.
System: Fedora 31 KDE
![proton_bridge](https://user-images.githubusercontent.com/5477747/79442952-7c675900-7fd9-11ea-92b0-dd782f3ca751.jpg)

**Comment by quicquid** [comment]
I have the same problem under F31 - it seems the font used is fontawesome (in its web version) but it doesn't work here either even though I have the fonts installed.

**Comment by horejsek** [comment]
Hi. Thanks for report. We know about this specific place which has problem on Fedora systems and is in our backlog. But you are saying `many interfaces where is not possible to read` - do you have an example of any other place with this problem?

**Comment by quicquid** [comment]
On my machine it's the general settings dialogue that is also rendered with that font:

![proton-fonts](https://user-images.githubusercontent.com/436903/79965205-431c6680-847b-11ea-80a9-1bf29cf662be.jpg)

All others seem to be ok.

**Comment by sagitter** [comment]
Confirm this bug on Fedora 32.

**Comment by andrzejsza** [comment]
we've been seeing quite a few weird issues with fonts on Fedora - we thought we fixed them all with 1.5.0 for Bridge and 1.2.2 for the I-E app. @Germano0 could you confirm if you still have those problems after updating?

**Comment by Germano0** [comment]
protonmail-bridge-1.5.2 has fixed almost all fonts problem. Except for some parts like login textboxes of user and password

**Comment by andrzejsza** [comment]
ok, thanks for confirming. you're still on Fedora 31 KDE?

**Comment by Germano0** [comment]
> ok, thanks for confirming. you're still on Fedora 31 KDE?

Fedora 33 KDE

**Comment by quicquid** [comment]
Im on Fedora 33 XFce and the fonts are fixed for me as well.

**Comment by quicquid** [comment]
Should we consider the issue to be closed?

**Comment by Germano0** [comment]
> Should we consider the issue to be closed?

No https://github.com/ProtonMail/proton-bridge/issues/13#issuecomment-738294459

**Comment by Germano0** [comment]
Confirming on 1.5.4

**Comment by andrzejsza** [comment]
all should be fixed now in 1.5.6, @Germano0 could you confirm?

**Comment by Germano0** [comment]
@andrzejsza  I confirm that 1.5.6 fixed the problem

**Comment by stellarhopper** [comment]
I still have this exact problem with the protonmail-import-export-app on Fedora 33.

Installed versions are:
```
$ protonmail-import-export-app --version
INFO[0000] Run app                                       appName="ProtonMail Import-Export" args="[protonmail-import-export-app --version]" build="2020-12-23T16:41:51+0000" pkg=cmd revision=9b82c03959 runtime=linux version=1.2.3
ProtonMail Import-Export version 1.2.3 (9b82c03959) 2020-12-23T16:41:51+0000

$ protonmail-bridge --version
INFO[0000] Run app                                       appName="ProtonMail Bridge" args="[protonmail-bridge --version]" build="2021-01-22T11:34:11+0000" pkg=cmd revision=645a8257d9 runtime=linux version=1.5.7
ProtonMail Bridge version 1.5.7 (645a8257d9) 2021-01-22T11:34:11+0000
```

**Comment by andrzejsza** [comment]
right. the I-E app is still waiting for a release that includes this fix - it will definitely be included in the next one.

**Comment by stellarhopper** [comment]
Ok - tried a local build from git, but that seems to be broken per #163 .. So I'll just wait.
