### ISSUE TITLE
Proton Bridge and mail.proton.me "read/unread" out of sync

### ISSUE THREAD

**Issue by AwlsomeAlex** [ProtonMail/proton-bridge#339]
One thread of 7 messages and another of 5 messages are out of sync with each other.
Proton.me reports they are unread, whereas both my mail clients have them marked as read.
The thread of 7 were caught with a custom filter, whereas the thread of 5 was caught by spam.

## Expected Behavior
Changes in the client should reflect in the website.

## Current Behavior
Discrepancy between website showing unread messages and client(s) showing all read.

## Possible Solution
N/A

## Steps to Reproduce
Not sure, kind of just happened out of the blue.

## Version Information
Proton Bridge v3.0.12
Proton 5.0.16.0 beta
Thunderbird 102.7.2
Apple Mail 16.0 (3731.400.51.1.1)

## Context (Environment)
macOS 13.2 (22D49) - Apple Silicon

Not sure if logs contain sensitive data. Can supply them if not.

**Comment by LBeernaertProton** [comment]
Hey @AwlsomeAlex , thank you for the report. Could you try again with the latest version (v3.0.16) or the latest beta (v3.0.17). We have fixed numerous problems since v3.0.12 :)

**Comment by AwlsomeAlex** [comment]
@LBeernaertProton I've this with the latest release (v3.0.18) and am still experiencing the issue. Thunderbird 110.0b4 says no unread messages, Proton web says 7 unread in my Spam folder.

**Comment by AwlsomeAlex** [comment]
@LBeernaertProton Hi, my issue appears to be solved. Thanks!

**Comment by AwlsomeAlex** [comment]
@LBeernaertProton Seems I called it fixed too early. Out of sync by 5 messages, seems to be related to my Proton filters.

**Comment by LBeernaertProton** [comment]
@AwlsomeAlex Could you provide details of your filters so we can try to replicate the problem?

Is this reproducible all the time on your end? If you were to add and remove the account, do you end up in the same state?

**Comment by AwlsomeAlex** [comment]
@LBeernaertProton It's a catchall for a mailing list. Three separate filters where it filters an email address from the sender or recipient (due to the nature of a mailing list).

```
require ["include", "environment", "variables", "relational", "comparator-i;ascii-numeric", "spamtest"];
require ["fileinto", "imap4flags"];

# Generated: Do not run this script on spam messages
if allof (environment :matches "vnd.proton.spam-threshold" "*", spamtest :value "ge" :comparator "i;ascii-numeric" "${1}") {
    return;
}

/**
 * @type or
 * @comparator contains
 * @comparator contains
 */
if anyof (address :all :comparator "i;unicode-casemap" :contains "From" "tech@openbsd.org", address :all :comparator "i;unicode-casemap" :contains ["To", "Cc", "Bcc"] "tech@openbsd.org") {
    fileinto "OpenBSD Mailing List/Tech";
}
```

Re-adding the account didn't correct it.

**Comment by AwlsomeAlex** [comment]
@LBeernaertProton Thunderbirds now reporting MORE messages than Proton web (25 in All Mail v. 18). This is using Bridge 3.0.19.

**Comment by LBeernaertProton** [comment]
@AwlsomeAlex do you have any errors in your logs? You can grep/search for the lines with `level=error`.

**Comment by LBeernaertProton** [comment]
@AwlsomeAlex Thank you for the logs. We have reproduced the issue and are working on a fix.

**Comment by munrad** [comment]
when using python, the imaplib library, the following construction helped:
`   _, data = conn.fetch(i, 'FLAGS')
    if not data or not data:
        return
    if 'seen' in data[0].decode().lower():
        conn.store(i, '-FLAGS', '(\\Seen)')
    conn.store(i, '+FLAGS', '(\\Seen)')
`

**Comment by LBeernaertProton** [comment]
A fix for this issue will be available in the next release (3.20). It is recommended that accounts are removed and added again  to correct the divergent state after update.
