### ISSUE TITLE
Thunderbird unable to reconnect to mailbox after logout/login in bridge

### ISSUE THREAD

**Issue by mattiaverga** [ProtonMail/proton-bridge#370]
Every time I logout from my account in bridge and re-login again, I get the same password to reconfigure Thunderbird in bridge GUI, yet Thunderbird is unable to reconnect to mailbox. I have to delete the account in Thunderbird and recreate it.
This is really annoying because I found bridge randomly logged out at computer startup. Upgrading to 3.0.21 shows the same behavior.

## Version Information
Bridge 3.0.21
Thunderbird 102.9.0

**Comment by pschweitz** [comment]
Hello, I have the same issue for several days as it was working fine so far, until I had to re-login in the bridge.

It's quite annoying, Thunderbird says "checking mail server capabilities" and remains idle.

Bridge 3.0.21
Thunderbird 102.8.0 (64-bit)
Ubuntu Mate 22.04.2

Thanks.

**Comment by pschweitz** [comment]
> Hello, I have the same issue for several days as it was working fine so far, until I had to re-login in the bridge.
> 
> It's quite annoying, Thunderbird says "checking mail server capabilities" and remains idle.
> 
> Bridge 3.0.21 Thunderbird 102.8.0 (64-bit) Ubuntu Mate 22.04.2
> 
> Thanks.

Well I got the problem fixed by inspiring from another readme content with caches locations. 
I actually deleted everything under ~/.cache/protonmail/bridge-v3 and ~/cache/ProtonMail*

Then killed and restarted the bridge.
Hope that can help

**Comment by LBeernaertProton** [comment]
Hey @mattiaverga I have personally run into a couple of issues with Thunderbird where if the Bridge certificate for IMAP and SMTP changes, Thunderbird does not detect this and I experienced the exact same problem. 

Can you go into `Settings > Privacy & Security > Manage Certificates > Servers`  and delete the entries for Bridge. Restart Thunderbird.  

Can you check if this solves the issue for you?

**Comment by mattiaverga** [comment]
> Hey @mattiaverga I have personally run into a couple of issues with Thunderbird where if the Bridge certificate for IMAP and SMTP changes, Thunderbird does not detect this and I experienced the exact same problem.
> 
> Can you go into `Settings > Privacy & Security > Manage Certificates > Servers` and delete the entries for Bridge. Restart Thunderbird.
> 
> Can you check if this solves the issue for you?

That was one of the things I tried and did not solve the problem.
However, I previously had changed the keyring to use secret-service instead of secret-service-dbus because of the bug with bridge 3.0.20. With 3.0.21 I had reverted to use secret-service-dbus and manually logging out/in doesn't trigger the problem anymore.

As I'm unable to manually reproduce the problem you may want to close the issue. If I encounter the issue again I'll reopen it.
