### ISSUE TITLE
Fix various message/MIME based errors

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#8]
The parser for message/MIME should be more graceful or maybe better - not even parser what it does not need and leave it as is.

**I think it should fail only when it would prevent encryption of the message and for that, you just really need to separate headers and body.**

I suggest making this aggregate of all message/MIME parsing errors or maybe this should move to the sub-projects.

1. "multipart: unexpected line in Next(): %q" - relates to go-message repository.
I think this relates to the multipart/mixed inside multipart/mixed.
2. "non-utf8 content without charset specification" - relates to go-mail repository.
This seems to be related to either missing charset or charset on the new line.
This actually fixes "reformime -r7" so.
3. "mime: duplicate parameter name" - not sure where this is coming.

These errors usually prevent the email to be imported through the bridge.

I can supply test files 1. and 2.

**Comment by cuthix** [comment]
It is planned to fix this (internal reference GODT-99)

**Comment by andrzejsza** [comment]
this was fixed with migrating to go-message.

**Comment by exander77** [comment]
@andrzejsza Should I retest, this was was still present when I tested new parser.

**Comment by andrzejsza** [comment]
would be great to confirm on the same exact messages, if possible? I didn't spot those errors in your #127  (apart from #126 )
